sulu_form.list:
    type: rest
    resource: sulu_form.list_controller
    prefix: form
    name_prefix: sulu_form.

sulu_form.forms:
    type: rest
    resource: sulu_form.form_controller
    name_prefix: sulu_form.

sulu_form.post_form_trigger:
    path: /forms/{id}.{_format}
    methods: POST
    defaults:
        _controller: sulu_form.form_controller::postTriggerAction
        _format: json

sulu_form.dynamic:
    type: rest
    resource: sulu_form.dynamic_controller
    prefix: form
    name_prefix: sulu_form.
